### ISSUE TITLE
Makefile docker-build looks broken

### ISSUE THREAD

**Issue by Dioprz** [Crypto-TII/CryptographicEstimators#142] opened 2024-05-08 00:21 UTC
Hi,

Just want to report that trying to install the project via docker I ended up with this error:

```fish
❯ make docker-build
Makefile:63: warning: overriding recipe for target 'docker-build'
Makefile:18: warning: ignoring old recipe for target 'docker-build'
make[1]: Entering directory '/home/user/Git/CryptographicEstimators'
Makefile:63: warning: overriding recipe for target 'docker-build'
Makefile:18: warning: ignoring old recipe for target 'docker-build'
Unable to find image 'estimators-lib:latest' locally
docker: Error response from daemon: pull access denied for estimators-lib, repository does not exist or may require 'docker login': denied: requested access to the resource is denied.
See 'docker run --help'.
make[1]: *** [Makefile:60: mount-volume-and-run] Error 125
make[1]: Leaving directory '/home/user/Git/CryptographicEstimators'
make: *** [Makefile:63: docker-build] Error 2
```

To solve it I have to remove `docker-build`  on the Makefile from here:

```fish
docker-doc docker-build:
	@make mount-volume-and-run && make generate-documentation && make stop-container-and-remove container_name="container-for-docs"
```

It's happening both in the `main` and `develop` branches.

**Comment by FloydZ** [comment] 2024-05-08 09:19
Thanks for raising this. This error should be fixed with [this](https://github.com/Crypto-TII/CryptographicEstimators/pull/136).
The problem is the line:
```
docker-doc docker-build:
```

which should be:
```
docker-doc: docker-build
```

I dont know why this change is already in `main`

**Comment by Dioprz** [comment] 2024-05-08 09:44
Yes, it works installing from your branch.

I think is good to have this open while the PR is merged, but it now is linked.

Thanks!

**Closed** 2024-05-15 06:36 UTC
